# Reference variable for use in training. It's an excerpt of Angie by the Rolling Stones
instrument_reference = ['live_loop :ref do\n', 'use_synth :', 'INSTRUMENTGOESHERE', '\n', 'with_fx :', 'none', ' do\n',
                        'sleep', 0.5, '\n',
                        'play', 57, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 3,
                        'decay: ', 0.4, '\n',
                        'sleep', 0.0, '\n',
                        'play', 60, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.0, '\n',
                        'play', 64, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.2,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.0, '\n',
                        'play', 45, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 3,
                        'decay: ', 0.4, '\n',
                        'sleep', 0.3, '\n',
                        'play', 64, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.3, '\n',
                        'play', 64, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.0, '\n',
                        'play', 60, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.0, '\n',
                        'play', 57, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.2,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.3, '\n',
                        'play', 60, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.0, '\n',
                        'play', 64, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.0, '\n',
                        'play', 67, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.3, '\n',
                        'play', 57, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.3, '\n',
                        'play', 60, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.3, '\n',
                        'play', 52, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.1, '\n',
                        'play', 52, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.01, '\n',
                        'play', 40, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.3, '\n',
                        'play', 59, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.2, '\n',
                        'play', 62, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.2, '\n',
                        'play', 64, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n',
                        'sleep', 0.2, '\n',
                        'play', 62, 'amp: ', 1.0, 'pan: ', 0, 'release: ', 0.1, 'attack: ', 0.01, 'sustain: ', 0.3,
                        'decay: ', 0.1, '\n', 'end\nend\n'
                        ]
# We'll give it a six. It needs tuning.
instrument_rating = 6
