# Reference variable for use in training. It's an excerpt of Megalovania by Toby Fox.
# Instrument size = 288 sleep and plays.
instrument_reference_name = "Megalovania"
instrument_reference = ['live_loop :ref do\n', 'use_synth :', 'INSTRUMENTGOESHERE', '\n', 'with_fx :', 'none', ' do\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 68, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 60, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 60, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 68, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 59, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 59, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 68, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 58, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 58, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 68, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 68, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 60, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 60, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 68, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 59, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 59, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 68, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 58, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 58, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 68, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 62, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 72, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 72, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 71, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 71, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 70, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 70, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 72, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 72, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 71, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 71, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 70, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 70, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.8, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 84, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.48, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 1.44, '\n',
                        'play ', 84, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.8, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.8, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 86, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 84, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 76, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 70, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 72, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 70, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 1.44, '\n',
                        'play ', 72, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 1.44, '\n',
                        'play ', 76, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 1.44, '\n',
                        'play ', 84, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.08, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.08, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.08, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.08, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 1.28, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 1.28, '\n',
                        'play ', 72, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 84, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 74, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 76, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 81, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 84, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 85, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 73, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 80, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.16, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 1.44, '\n',
                        'play ', 79, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 1.44, '\n',
                        'play ', 75, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 67, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 65, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 69, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n',
                        'sleep ', 0.32, '\n',
                        'play ', 77, ', amp: ', 1, ', pan: ', 0, ', release: ', 0.1, ', attack: ', 0, ', sustain: ',
                        0.05,
                        ', decay: ', 0, '\n', 'end\nend\n'
                        ]
# We'll give it a 8. Not bad.
instrument_rating = 8
